### Create Address

POST http://localhost:3000/api/contacts/235/addresses
Content-Type: application/json
Accept: application/json
Authorization: 98aba947-c57e-4128-a4fa-0d73ae721503

{
  "street": "Kantor",
  "city": "Jakarta",
  "province": "DKI JAKARTA",
  "country": "Indonesia",
  "postal_code": "324234"
}

### List Addresses

GET http://localhost:3000/api/contacts/235/addresses
Content-Type: application/json
Accept: application/json
Authorization: 98aba947-c57e-4128-a4fa-0d73ae721503

### Get Address

GET http://localhost:3000/api/contacts/235/addresses/29
Content-Type: application/json
Accept: application/json
Authorization: 98aba947-c57e-4128-a4fa-0d73ae721503

### Update Address

PUT http://localhost:3000/api/contacts/235/addresses/29
Content-Type: application/json
Accept: application/json
Authorization: 98aba947-c57e-4128-a4fa-0d73ae721503

{
  "street": "Kantor Bekerja",
  "city": "Bekasi",
  "province": "Jawa Barat",
  "country": "Indonesia",
  "postal_code": "324234"
}

### Remove Address

DELETE http://localhost:3000/api/contacts/235/addresses/29
Content-Type: application/json
Accept: application/json
Authorization: 98aba947-c57e-4128-a4fa-0d73ae721503